<a href="https://colab.research.google.com/github/NikunjRathod200/Machine-Learning/blob/main/Blast_Mine_and_Rock_Prediction_from_Sonar_Data_%7C_Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Sonar%20Mine%20Rock%20Data.csv")

In [3]:
df.head()

X1      X2      X3      X4      X5      X6      X7      X8      X9  \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

      X10  ...     X52     X53     X54     X55     X56     X57     X58  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

      X59     X60  y  
0  0.0090  0.0032  R  
1  0.0052  0.0044  R  
2  0.0095  0.0078  R  
3  0.0040  0.0117  R  
4  0.0107  0.0094  R  

[5 rows x 61 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      208 non-null    float64
 1   X2      208 non-null    float64
 2   X3      208 non-null    float64
 3   X4      208 non-null    float64
 4   X5      208 non-null    float64
 5   X6      208 non-null    float64
 6   X7      208 non-null    float64
 7   X8      208 non-null    float64
 8   X9      208 non-null    float64
 9   X10     208 non-null    float64
 10  X11     208 non-null    float64
 11  X12     208 non-null    float64
 12  X13     208 non-null    float64
 13  X14     208 non-null    float64
 14  X15     208 non-null    float64
 15  X16     208 non-null    float64
 16  X17     208 non-null    float64
 17  X18     208 non-null    float64
 18  X19     208 non-null    float64
 19  X20     208 non-null    float64
 20  X21     208 non-null    float64
 21  X22     208 non-null    float64
 22  X2

In [5]:
df.describe()

X1          X2          X3          X4          X5          X6  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               X7          X8          X9         X10  ...         X51  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

              X52         X53         X54         X55         X56         X57  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

              X58         X59         X60  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [7]:
df.columns

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11',
       'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21',
       'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31',
       'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41',
       'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51',
       'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'y'],
      dtype='object')

In [8]:
df.shape

(208, 61)

In [9]:
df['y'].value_counts()

M    111
R     97
Name: y, dtype: int64

In [11]:
df.groupby('y').mean()

X1        X2        X3        X4        X5        X6        X7  \
y                                                                         
M  0.034989  0.045544  0.050720  0.064768  0.086715  0.111864  0.128359   
R  0.022498  0.030303  0.035951  0.041447  0.062028  0.096224  0.114180   

         X8        X9       X10  ...       X51       X52       X53       X54  \
y                                ...                                           
M  0.149832  0.213492  0.251022  ...  0.019352  0.016014  0.011643  0.012185   
R  0.117596  0.137392  0.159325  ...  0.012311  0.010453  0.009640  0.009518   

        X55       X56       X57       X58       X59       X60  
y                                                              
M  0.009923  0.008914  0.007825  0.009060  0.008695  0.006930  
R  0.008567  0.007430  0.007814  0.006677  0.007078  0.006024  

[2 rows x 60 columns]

In [12]:
y = df['y']

In [13]:
y.shape

(208,)

In [14]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: y, Length: 208, dtype: object

In [15]:
X= df[['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11',
       'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21',
       'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31',
       'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41',
       'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51',
       'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60']]

In [16]:
X.shape

(208, 60)

In [17]:
X

X1      X2      X3      X4      X5      X6      X7      X8      X9  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

        X10  ...     X51     X52     X53     X54     X55     X56     X57  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

        X58     X59     X60  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss = StandardScaler()

In [20]:
X = ss.fit_transform(X)

In [21]:
X

array([[-0.39955135, -0.04064823, -0.02692565, ...,  0.06987027,
         0.17167808, -0.65894689],
       [ 0.70353822,  0.42163039,  1.05561832, ..., -0.47240644,
        -0.44455424, -0.41985233],
       [-0.12922901,  0.60106749,  1.72340448, ...,  1.30935987,
         0.25276128,  0.25758223],
       ...,
       [ 1.00438083,  0.16007801, -0.67384349, ...,  0.90652575,
        -0.03913824, -0.67887143],
       [ 0.04953255, -0.09539176,  0.13480381, ..., -0.00759783,
        -0.70402047, -0.34015415],
       [-0.13794908, -0.06497869, -0.78861924, ..., -0.6738235 ,
        -0.29860448,  0.99479044]])

In [22]:
from sklearn.model_selection import train_test_split as tts

In [23]:
X_train,X_test, y_train,y_test = tts(X,y,test_size=0.3, random_state= 2529)

In [24]:
X_train.shape,X_test.shape, y_train.shape,y_test.shape

((145, 60), (63, 60), (145,), (63,))

In [26]:
from sklearn.naive_bayes import GaussianNB

In [27]:
nb = GaussianNB()

In [28]:
nb.fit(X_train,y_train)

GaussianNB()

In [29]:
y_pred = nb.predict(X_test)

In [30]:
y_pred

array(['M', 'M', 'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'M', 'R', 'R',
       'M', 'M', 'R', 'M', 'R', 'R', 'M', 'R', 'R', 'R', 'R', 'M', 'R',
       'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'R', 'R',
       'M', 'R', 'R', 'M', 'R', 'M', 'R', 'R', 'R', 'R', 'R', 'M', 'R',
       'R', 'M', 'R', 'M', 'R', 'M', 'M', 'M', 'R', 'R', 'M'], dtype='<U1')

In [31]:
nb.predict_proba(X_test)

array([[9.26638177e-01, 7.33618228e-02],
       [9.99998029e-01, 1.97093898e-06],
       [1.23519439e-03, 9.98764806e-01],
       [9.60833900e-01, 3.91660997e-02],
       [6.94699423e-10, 9.99999999e-01],
       [9.99986123e-01, 1.38770642e-05],
       [4.65772379e-08, 9.99999953e-01],
       [4.04712361e-01, 5.95287639e-01],
       [5.49103644e-07, 9.99999451e-01],
       [4.03297260e-05, 9.99959670e-01],
       [1.00000000e+00, 4.35660603e-12],
       [8.36848424e-08, 9.99999916e-01],
       [9.02694182e-04, 9.99097306e-01],
       [1.00000000e+00, 2.78332974e-11],
       [6.15058370e-01, 3.84941630e-01],
       [2.36837408e-03, 9.97631626e-01],
       [1.00000000e+00, 1.04387874e-19],
       [2.51130702e-03, 9.97488693e-01],
       [2.47834677e-02, 9.75216532e-01],
       [6.44711723e-01, 3.55288277e-01],
       [2.77293027e-02, 9.72270697e-01],
       [3.52903197e-03, 9.96470968e-01],
       [6.61351559e-04, 9.99338648e-01],
       [9.72587717e-08, 9.99999903e-01],
       [9.914740

In [32]:
from sklearn.metrics import confusion_matrix, classification_report

In [33]:
confusion_matrix(y_pred,y_test)

array([[19,  5],
       [14, 25]])

In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           M       0.79      0.58      0.67        33
           R       0.64      0.83      0.72        30

    accuracy                           0.70        63
   macro avg       0.72      0.70      0.70        63
weighted avg       0.72      0.70      0.69        63

